import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './styles/globals.css'
import React from "react";
import { Providers } from "./Redux/Provider";
import PageTransitionEffect from "./(Pages)/_app";
import Header from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-black">
        <Providers>
       <PageTransitionEffect>  
        <Header />
        {/* <div className="bg-gradient-to-b  from-gray-800 via-black  to-gray-800  "> */}
            {children} 
        {/* </div> */}
        <Footer />
         </PageTransitionEffect>
        </Providers>
      </body>
    </html>
  );
}
